### PR TITLE
fix embeds.xml & WeakAuras.toc packaging conditions for classic

### PR DESCRIPTION
**Pull request by mrbuds**
Fix libclassiccast & libclassicdurations not loading
Fix .toc files trying to load Model & ModelPicker files

Following error needs to be fixed upstream (or fork?)

```
2x ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1049: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
[C]: in function `RegisterEvent'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1049: in function `activate'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1093: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "PLAYER_TALENT_UPDATE"
```

### CODE REVIEW

**Comment by emptyrivers** [comment]
Are you sure this is the right fix? That looks backwards to me.

**Comment by mrbuds** [comment]
Yes, right now embeds.xml condition is commented on classic
```xml
  <!--@retail
  <Include file="Libs\LibClassicDurations\LibClassicDurations.xml"/>
  <Include file="Libs\LibClassicCast\lib.xml"/>
  @end-retail@-->
```
And WeakAuras.toc try to load Model.lua

**Comment by emptyrivers** [comment]
The thing is, that I would expect the retail package to also be broken if we’ve been using that tag incorrectly. If only the classic package is broken. Then that sounds like an issue with our packaging script not interpreting the tags correctly.

**Comment by InfusOnWoW** [comment]
The fix looks correct to me, I would expect
<--@retail [...] @retail --> to mean that whatever is between those tags should be included for retail.

**Comment by mrbuds** [comment]
"I would expect the retail package to also be broken" > retail package try to load the 2 extra libs in embeds.xml but doesn't ship them
.toc files changes were an omission

**Pull request merged**
