### PR TITLE
Add option to modify aura version

### PR DESCRIPTION
**Pull request by Vardex**
# Description

This add an option in the information tab, to modify the version that is shown on the tooltip of an aura.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

- [x] Changed version of a single aura
- [x] Changed version of a group

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mrbuds** [comment]
I don't get what it solve, why not leave it to wago ?

**Comment by Vardex** [comment]
Don't really know but recently, description and url modification was added. Version is the only things that the user see on their aura and that they can't change.

I only made that PR because someone asked how to change that version and I had to tell them to edit their sv.

**Comment by InfusOnWoW** [comment]
Well, that's intentionally, it's data that is maintained on wago's side.

**Comment by Vardex** [comment]
You could say the same for url, it was something that was added by wago and couldn't be modified in game.

**Comment by InfusOnWoW** [comment]
You are right. I relented on url because too many people wanted to change the url. I guess the same rational is true for version too.

What was the difference between semversion and version? semversion is what the user sets and version just the incremented number?

**Comment by mrbuds** [comment]
> What was the difference between semversion and version? semversion is what the user sets and version just the incremented number?

companion & weakauras use "semver" for display/information for user only
"version" is use by both to compare which aura for same "slug" is the newest

**Comment by emptyrivers** [comment]
Related #1881

**Comment by InfusOnWoW** [comment]
This needs:

* Coordination with @oratory so that if a export with a semVer is pasted into the "Import new version" dialog, the semver from the import is used. (If valid)
* A validation in WeakAuras to ensure that the format stays a dotted 3 number list or whatever the right format is.

**Comment by oratory** [comment]
> * Coordination with @oratory so that if a export with a semVer is pasted into the "Import new version" dialog, the semver from the import is used. (If valid)

I can add something to wago to look for a manually changed version.

> * A validation in WeakAuras to ensure that the format stays a dotted 3 number list or whatever the right format is.

It should also check that the new version is greater than the current version, or wago won't use it.

**Comment by InfusOnWoW** [comment]
Nah, we don't want a "increase" check in wa. As one of the use cases is to "reset" the version to 1.0.0.

**Comment by oratory** [comment]
Ah that makes sense, Wago would just ignore it if it's not an increase then.

**Comment by InfusOnWoW** [comment]
Closing for now, since it wasn't update in a long time.

**Pull request closed without merging**
