### PR TITLE
Add WeakAuras Import UI

### PR DESCRIPTION
**Pull request by mrbuds**
# Description

Add a WeakAuras.StashShow function that WeakAurasCompanion can use when there are auras pushed from Wago with weakauras-companion://wago/push/<wagoID>

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How to test

- get last companion build (current https://github.com/WeakAuras/WeakAuras-Companion/suites/2521299971/artifacts/54607460)
- go to https://wago.io/d3cV99LwL
- ctrl+shift+k on firefox to open dev console and type/run `enableCompanion = true`
image

- press button "SEND TO WEAKAURA COMPANION APP"
image

- unfinished UI show in companion
image

- /reload in game
image

## TODO in WeakAuras
- make less ugly UI

## TODO in Companion
- make less ugly UI

### CODE REVIEW

**Comment by Stanzilla** [comment]
Nice! I think the ultimate goal was to have it as a section in the normal UI above `Loaded` not sure if we need that to ship a v1

**Comment by mrbuds** [comment]
> 
> 
> Nice! I think the ultimate goal was to have it as a section in the normal UI above `Loaded` not sure if we need that to ship a v1

You mean like this ?
image

**Comment by Stanzilla** [comment]
yes!

**Comment by AcidWeb** [comment]
image
Is returned by companion when slug is containing `+`.

https://wago.io/M+Timer

**Pull request merged**
