### PR TITLE
**WIP Provide Specialization filter for BT2, Health, Power triggers

### PR DESCRIPTION
**Pull request by InfusOnWoW**
Built on top of LibSpecialization.

Note: Needs a more advanced LibSpecialization

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
@funkydude This is more or less finished and works as far as my testing checked.

**Comment by mrbuds** [comment]
Can you add the lib to WeakAuras.IsLibsOK function?

**Comment by InfusOnWoW** [comment]
> Can you add the lib to WeakAuras.IsLibsOK function?

Done.

**Comment by InfusOnWoW** [comment]
Now that LibSpecialization is there, I put it into my normal PR:
https://github.com/WeakAuras/WeakAuras2/pull/3720

**Pull request closed without merging**
