### PR TITLE
Rework Magnetic Edit

### PR DESCRIPTION
**Pull request by InfusOnWoW**

### CODE REVIEW

**Comment by Stanzilla** [comment]
Can we make it so the line turns red if it's the middle of the screen?

**Comment by InfusOnWoW** [comment]
You mean add a line for middle of screen? I did include a full grid option, and at the end disabled it, see the booleans at the top of MoverSizer.lua

**Comment by Stanzilla** [comment]
> You mean add a line for middle of screen? I did include a full grid option, and at the end disabled it, see the booleans at the top of MoverSizer.lua

Not quite, I saw the option and figured as a middle ground of showing the full grid or not, we can just color the middle lines horizontal and vertical, in a different color when snapping to them so it's easy to see they are the middle

**Comment by mrbuds** [comment]
First single icon with no group i try to move i get this error

```
1x WeakAurasOptions/OptionsFrames/MoverSizer.lua:693: attempt to perform arithmetic on local 'centerX' (a nil value)
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:693: in function `CreateLineInformation'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:814: in function `CreateLines'
[string "@WeakAurasOptions/OptionsFrames/MoverSizer.lua"]:1213: in function <WeakAurasOptions/OptionsFrames/MoverSizer.lua:1196>

Locals:
self = Frame {
 0 = <userdata>
 linePool = <table> {
 }
 CleanUpLines = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:790
 horizontalLines = <table> {
 }
 CreateLines = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:806
 CreateGridLines = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:625
 CreateLineInformation = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:667
 ShowLinesFor = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:889
 MergeLineInformation = <function> defined @WeakAurasOptions/OptionsFrames/MoverSizer.lua:748
 verticalLines = <table> {
 }
}
data = <table> {
 iconSource = -1
 color = <table> {
 }
 yOffset = 472.499878
 anchorPoint = "CENTER"
 cooldownSwipe = true
 cooldownEdge = false
 icon = true
 triggers = <table> {
 }
 internalVersion = 65
 keepAspectRatio = false
 selfPoint = "CENTER"
 desaturate = false
 subRegions = <table> {
 }
 height = 64
 load = <table> {
 }
 regionType = "icon"
 cooldown = true
 xOffset = 3.750305
 actions = <table> {
 }
 displayIcon = 607513
 zoom = 0
 cooldownTextDisabled = false
 useCooldownModRate = true
 config = <table> {
 }
 id = "Gateway Control Shard"
 anchorFrameType = "SCREEN"
 frameStrata = 1
 width = 64
 alpha = 1
 uid = "f1BpR6tR)22"
 inverse = false
 authorOptions = <table> {
 }
 conditions = <table> {
 }
 information = <table> {
 }
 animation = <table> {
 }
}
sizerPoint = nil
addVertical = true
addHorizontal = true
horizontalLines = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
}
verticalLines = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
 24 = <table> {
 }
 25 = <table> {
 }
 26 = <table> {
 }
 27 = <table> {
 }
 28 = <table> {
 }
 29 = <table> {
 }
 30 = <table> {
 }
 31 = <table> {
 }
 32 = <table> {
 }
 33 = <table> {
 }
 34 = <table> {
 }
 35 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 38 = <table> {
 }
 39 = <table> {
 }
 40 = <table> {
 }
 41 = <table> {
 }
 42 = <table> {
 }
 43 = <table> {
 }
 44 = <table> {
 }
 45 = <table> {
 }
 46 = <table> {
 }
 47 = <table> {
 }
 48 = <table> {
 }
 49 = <table> {
 }
 50 = <table> {
 }
 51 = <table> {
 }
 52 = <table> {
 }
 53 = <table> {
 }
 54 = <table> {
 }
 55 = <table> {
 }
 56 = <table> {
 }
 57 = <table> {
 }
 58 = <table> {
 }
 59 = <table> {
 }
 60 = <table> {
 }
}
skipIds = <table> {
 Gateway Control Shard = true
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 Vault of the Incarnates Tank Aura Group = <table> {
 }
 Shadow
```

**Comment by mrbuds** [comment]
reproduction steps:

- /reload
- /wa
- click single aura icon
- click on visibility toggle of my "evoker" normal group that contains multiple dynamic groups
- move first icon aura => error


https://user-images.githubusercontent.com/189656/227789829-dce700d2-8d09-451c-861b-f54aed29ccac.mp4

**Comment by mrbuds** [comment]
> > You mean add a line for middle of screen? I did include a full grid option, and at the end disabled it, see the booleans at the top of MoverSizer.lua
> 
> Not quite, I saw the option and figured as a middle ground of showing the full grid or not, we can just color the middle lines horizontal and vertical, in a different color when snapping to them so it's easy to see they are the middle

previous code had coords for horizontal/vertical line of middle of screen align
```
  local midX, midY = UIParent:GetCenter()
  tinsert(x, midX)
  tinsert(y, midY)
```

**Comment by InfusOnWoW** [comment]
I added a center line (with a different color), and also fixed the lua error.

I didn't fix the issue that translit noticed that in the demo gif somehow (probably uiscale) the icons ended up misaligned. I'll need some time to figure out what happened and to think about the problem. It shouldn't really affect general feedback on how the drag/dropping feels now though.

**Review by mrbuds — APPROVED** [review]

**Review by Stanzilla — APPROVED** [review]

**Pull request merged**
