### PR TITLE
add text replacements to message_dest

### PR DESCRIPTION
**Pull request by asaka-wa**
# Description

I don't know if anyone ever made a ticket for it but people often want to use text replacements in the "Send To" setting when using Chat Message - Whisper. Most commonly stuff like using a whisper to reply to the person that just cast something on you or whatever. I'd always assumed this was too tricky or awkward to do but when doing the recent TTS PR I noticed it wasn't so awkward after all. 

~~The only awkwardness was having to remove the handling of `%t` that was already in. In defence of this I don't know if anyone knew this was an available option. I've certainly never seen anyone use it.~~ 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
You didn't consider the %c special case.

**Comment by asaka-wa** [comment]
Ah, yes. I'll look at that next week.

**Comment by asaka-wa** [comment]
This is actually likely to overlap with the TTS stuff a bit so I'll wait until that's in then return to this. 
Actions was simple enough. Conditions trickier but ultimately it's all got to be sent forward into the Chat Handler.

**Comment by InfusOnWoW** [comment]
@asaka-wa ping

**Comment by asaka-wa** [comment]
I intend to finish this once the TTS stuff is live as I think it'll require adjusting some of the same functions.

**Pull request closed without merging**
