### PR TITLE
handle DBM & BW pause/resume callbacks

### LINKED ISSUE #2951: Add support for DBM pausing timers
**Is your feature request related to a problem? Please describe.**
DBM triggers are still firing even though the timer has paused.

**Describe the solution you'd like**
I would like to see WA updated to support DBM paused timers.

**Additional context**
https://github.com/DeadlyBossMods/DeadlyBossMods/commit/ed1ae7ba2ae58d282de3e6134718fd36313fab20

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
As I don't think we have a way to pause a timed aura, this will handle DBM_TimerPause like a DBM_TimerStop event, and DBM_TimerResume like a DBM_TimerStart event
and same for BigWigs_PauseBar and BigWigs_ResumeBar events

fixes #2951

I have not tested the change since it seems dbm will only fire them for a mythic boss i won't do

### CODE REVIEW

**Comment by mrbuds** [comment]
Bigwigs implemented pause/resume of timers as well, i need to handle it

**Comment by InfusOnWoW** [comment]
I don't quite understand what pause+resume does. 

Is the bar still visible while paused?

**Comment by mrbuds** [comment]
> 
> 
> I don't quite understand what pause+resume does.
> 
> Is the bar still visible while paused?

Both addon call Pause() and Resume() functions in libcandybar
```
--- Pauses a running bar
function barPrototype:Pause()
	if not self.paused then
		self.updater:Pause()
		self.paused = true
	end
end
--- Resumes a paused bar
function barPrototype:Resume()
	if self.paused then
		self.exp = GetTime() + self.remaining
		self.updater:Play()
		self.paused = nil
	end
end
```

So it seems yes bars stay on screen but stop their animation.
My PR is not doing that, it shortcut pause/resume to make them a stop/start, i don't know how complex it is to have same behavior as they do

**Comment by InfusOnWoW** [comment]
Well, currently the auras don't support being paused/resumed at all. 

Adding support for it shouldn't be impossible, though currently state is suposed to contain a expirationTime. We would need to support e.g. having paused + remaining in the state, which if set are used instead of expirationTime.

Looking at the code, that would require changes in ProgressTexture/AuraBar/Icon/Tick and for %p.

That doesn't look too bad. Do you want to do that?

**Comment by mrbuds** [comment]
That sound like a nice little project i can work on it

**Comment by mrbuds** [comment]
So i have a working patch for pausing auras as you can see in this clip https://clips.twitch.tv/AmericanSlipperyMeerkatOneHand-iedtMRl60OJD-2rw that needs a bit more thoughts.

But after looking at dbm & bw timer triggers implementation in weakauras, especially for no-clones that use a lot of recheck scheduling to detect shortest duration matching bar, it's not going to be that easy

**Comment by InfusOnWoW** [comment]
Well for the rechecking scheduling, you have to skip over all paused clones. 

And obviously recheck the scheduling on both Pause and Resume.

**Comment by mrbuds** [comment]
i'v pushed the state.paused commit so you can have a look

**Comment by mrbuds** [comment]
Bigwigs & DBM pause/resume is implemented
I used this group for tests https://wago.io/GUJCuatgb

**Comment by MysticalOS** [comment]
For time being i added a clone of DBT.Options to DBM.Bars.options for backwards compat.

as for testing dbm pause/resume. you don't need to do boss, the one boss that does it has debug functions built in. just load castle mods then run the scripts from lua file.

for example

`/run DBM:GetModByName(2426):TestRestart(30)`
to start timers
`/run DBM:GetModByName(2426):TestPause()`
to pause them
`/run DBM:GetModByName(2426):TestResume()`
to resume them

also if whlie add it you want to teset add and remove time objects tests for those exist too.

**Comment by mrbuds** [comment]
For dbm i used this dirty snippet to test pause/resume (included in https://wago.io/GUJCuatgb)
```
function(e)
    local bossName = "WA-DBM-TEST"
    local mod
    for k, v in pairs(DBM.Mods) do
        if v.id == bossName then
            mod = v
            break
        end
    end
    if not mod then
        mod = DBM:NewMod(bossName)
    end
    local cd = mod:NewCDTimer(5, 347350, "dbm wa test", nil, nil, 1)
    if e == "PLAYER_TARGET_CHANGED" then
        cd:Start()
    elseif e == "PLAYER_STARTED_MOVING" then
        cd:Pause() 
    elseif e == "PLAYER_STOPPED_MOVING" then
        cd:Resume() 
    end
end
```

**Comment by mrbuds** [comment]
@emptyrivers can you confirm if this is the correct fix for the tocversion field issue that was brought up a few days ago ?

**Comment by InfusOnWoW** [comment]
I had a quick look through the Pause code and it looks pretty good. I'll have to check a few details on some of the changes, but the general gist of it is very much how I think this should work.

**Comment by MysticalOS** [comment]
Slightly off topic but I did some talking with a bunch of users about the recent freezing in raids related to Council and at first I was confused because the new string of DBT anchor errors in DBM was annoying but never caused freezes. The anchoring issues themselves were annoying because they couldn't be reproduced by myself or QartemisT. But when a subset of a subset of users were getting a repeating freeze i was even more stumped.

Then I noticed a common demoninator. The DBT anchor lua errors could happen anytime during fight but the freeze the answer was always "I froze during dark ritual". Why was the subset of subset of users freezing there?

I put that out of mind though and rushed updated DBT code out that fixed anchoring. Anchoring all fixed. no one was getting DBT errors anymore about anchoring. They were getting some callback errors instead because weak auras couldn't find DBM.Bars.options . Whatever little details...But then they froze again at dark ritual. That's when it finally hit me the freeze and weak auras failing were related.

They were all running the popular dark ritual weak aura that triggers off DBM timer. Because DBT was failing to create/anchor the dark ritual timer correctly the weak aura deadlocking and that's what caused freeze. Then when I pushed fix to anchoring they still froze because now weak aura was still failing but for a totally different reason.

I imagine in both scenarios it was spitting out hundreds of errors. Whether the freeze happened because WA code execution didn't know wtf to do with that, or failure in DBM Callback code executing callbacks on our end I don't know. This is something I want to look into. Regardless the freezing should be resolved i believe with the rewrite code in DBT combined with updated weak aura code knowing where new options are, but I still want to get bottom of where the freeze occurs so that if timers fail, no matter how spectacularly neither weak auras or DBM callback code deadlocks from it. On your end I'd just maybe add a safe exit that goes "what is this shit data? that's not supposed to be nil or broken, ignore this trash" somewhere (as long as it isn't expensive) and I'll look at callback code to make sure it also doesn't execute stupid shit unthrottled.

**Comment by mrbuds** [comment]
@MysticalOS Do you have a link for this Dark Ritual aura and a copy of the error they get ?

**Comment by Justw8** [comment]
> Bigwigs implemented pause/resume of timers as well, i need to handle it
> 
> cf https://github.com/BigWigsMods/BigWigs/blob/b359a4470cf8d7a3ccb0730ecb014a73b33d4175/CastleNathria/TheCouncilofBlood.lua#L611

I know this is closed and done now, but since we had someone report an issue today which was fixed in a bugfix, I came across this and just wanted to add: Bigwigs has had pause/resume bars for over 6 years now. https://github.com/BigWigsMods/BigWigs/commit/8dea709b1798acbacba9813888a39cef6cbc14e1

**Pull request merged**
