### PR TITLE
GetHitChance : fix potential nil error

### PR DESCRIPTION
**Pull request by mrbuds**

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
That can return nil?

**Comment by mrbuds** [comment]
Yeah it's weird and i couldn't reproduce by running those lines manually, but after a dungeon on my mage which have an aura using this trigger, i had a Lua error for math operation with nil on bugsack.

**Comment by Stanzilla** [comment]
> Yeah it's weird and i couldn't reproduce by running those lines manually, but after a dungeon on my mage which have an aura using this trigger, i had a Lua error for math operation with nil on bugsack.

On PTR or live?

**Comment by mrbuds** [comment]
live

**Pull request merged**
