### PR TITLE
Add headers to bufftrigger2 to aid navigation of settings

### PR DESCRIPTION
**Pull request by asaka-wa**
# Description

Added headers to bufftrigger2's options and reordered some elements to better fit the discrete sections.     
Also changed the setting name "Debuff Type" to "Dispel Type" and added a couple of tooltips.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Nightwarden24** [comment]
If you change a name of the option (Debuff Type → Dispel Type), then be consistent and do it in all places related to that option. Some lines:

- [Link 1](https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/BuffTrigger2.lua#L2732)
- [Link 2](https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/BuffTrigger2.lua#L2733)
- [Link 3](https://github.com/WeakAuras/WeakAuras2/blob/main/WeakAuras/BuffTrigger2.lua#L2776)

**Comment by asaka-wa** [comment]
Before https://i.imgur.com/iakq2NR.gif
After https://i.imgur.com/NxGx1wm.gif

**Comment by mrbuds** [comment]
Debuff renamed Dispel make option name not match their text replacement anymore

**Comment by asaka-wa** [comment]
This is why I griped about Nightwarden's request 🤣

**Comment by Nightwarden24** [comment]
Well, then you will have Dispel Type on Trigger tab, Debuff Type on Condition tab and Debuff Class as text replacement on Display tab

**Comment by mrbuds** [comment]
> Well, then you will have Dispel Type on Trigger tab, Debuff Type on Condition tab and Debuff Class as text replacement on Display tab

I was suggesting to revert this tiny change, otherwise i like this PR

**Comment by Stanzilla** [comment]
@asaka-wa ah dang, the recent merge created a conflict, can you resolve please?

**Pull request merged**
