### PR TITLE
Smallerpatches

### PR DESCRIPTION
**Pull request by InfusOnWoW**

### CODE REVIEW

**Comment by Stanzilla** [comment]
I feel like `Player Effective Level` is not very clear to users

**Comment by InfusOnWoW** [comment]
You or Ironii need to suggest something better than...

**Comment by emptyrivers** [comment]
Just "Effective Level" with maybe a tooltip should do the job, I think.

**Comment by InfusOnWoW** [comment]
I've added a tooltip. I did keep the "Player" prefix, because most of the preceding options have it, and removing it from one probably is a bit strange.

**Pull request merged**
