### PR TITLE
Threat Situation trigger rework and enable it for WoW 1.13.5

### PR DESCRIPTION
**Pull request by mrbuds**
…e more informations

If unit is not "At Least One Enemy"
- use UNIT_THREAT_LIST_UPDATE instead of UNIT_THREAT_SITUATION_UPDATE
- use UnitDetailedThreatSituation instead of UnitThreatSituation
- %threatpct, %rawthreatpct and %threatvalue can be use
- duration function use threatpct

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
I'll take a look soon.

**Comment by InfusOnWoW** [comment]
Well I've been busy, I'm not sure about setting the statesParameter to "unit" yet, that feels a bit strange for a non-cloning trigger.

**Comment by Stanzilla** [comment]
When is 1.13.5 coming out?

**Comment by InfusOnWoW** [comment]
It's already out iirc.

**Comment by oratory** [comment]
It's not out yet, it's coming with AQ and related content. No timeline from Blizz yet but likely 4-5 weeks away still.

**Comment by mrbuds** [comment]
Why did you add the wrapper WeakAuras.UnitDetailedThreatSituation for UnitDetailedThreatSituation ?
I ask because later i'v added
```
  if not UnitDetailedThreatSituation then
    WeakAuras.event_prototypes["Threat Situation"] = nil
  end
```
which can be remove after 1.13.5 release

**Comment by InfusOnWoW** [comment]
Because it's too picky about the passed parameters. Calling UnitDetailedThreatSituation with "player", "any non unit string" results in a error, which makes using specific unit pretty error prone.

**Comment by Stanzilla** [comment]
July 27th is the Raid release

**Comment by mrbuds** [comment]
It doesn't need to wait for next patch to be merged

**Pull request merged**
