### PR TITLE
add buttons for moving auras by 1 pixel

### LINKED ISSUE #948: Add nudge buttons to aura mover
**Is your feature request related to a problem? Please describe.**
Basically it's a bit awkward at the moment to position aura and align it to something else (unitframe,bars,map,chat etc.) with pixel precision. If you want to move aura by like a pixel (or multiple) you have to go into display and type in offset value (using slider for 1 pixel most of the time is almost impossible). 

**Describe the solution you'd like**
Basically add something like this 

Just buttons for x/y next to aura mover that +/- 1 for respective offset axis. 
ElvUI for example has it like this 
 
But personally feel like it's too bulky

**Describe alternatives you've considered**
Alternative could be adding these buttons next to x/y offset slider in display

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
Add button for moving auras and groups by 1pxl to help build pixel perfect ui
preview

Fixes #948

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- [ ] Test A
- [ ] Test B

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Do you have suggestions for buttons texture, position, and mouseover + button press effect ?

### CODE REVIEW

**Comment by Stanzilla** [comment]
I like it!

**Comment by InfusOnWoW** [comment]
I found one small issue: The display tab's xoffset and yoffset don't update on clicking on the nudge button.

Otherwise this feels very nice!

**Comment by mrbuds** [comment]
prev
I added highlight and pressed textures, it feels a bit too much for my taste, what do you think ?

**Comment by Stanzilla** [comment]
I like it!

**Pull request merged**
