### PR TITLE
additional WA logo textures

### PR DESCRIPTION
**Pull request by Translitdk**
# Description

Additional WA logo textures. Default .blp is low res

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

Just some textures. Nothing special to test

## Checklist

no new code used

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
@mrbuds, @Stanzilla any opinion on this? I don't care either way.

**Comment by Stanzilla** [comment]
Fine by me tbh

**Comment by Stanzilla** [comment]
Don't think we need the 512 tbh? Nobody is going to use it that large and the file is also rather big

**Comment by mrbuds** [comment]
they need to be added to the texture selector

**Comment by Translitdk** [comment]
Added 512 one because i tried to use default one for background texture of EditBox and it was awful.

**Comment by mrbuds** [comment]
Added 64px & 256px to texture picker in a new "WeakAuras" entry and removed 512px version

**Pull request merged**
