### PR TITLE
Refactor progress handling

### PR DESCRIPTION
**Pull request by InfusOnWoW**
* Make progress data (that is expirationTime/duration/value/total/etc) far less special state properties
* Instead state metadata can now describe multiple properties as progress values and which other properties are relevant, e.g.

  charge = { display = "Charges", type = "number", total = "totalCharge" }

  will allow the user to select "charge" as progress source, which will automatically use state.totalCharge for the total value.

  Or

  someTime = { display = "X", type = "timer", total = "propertyName", modRate = "propertyName", inverse = "propertyName", paused = "propertyName", remaining = "propertyName" }

  All of the additional properties are optional.

  And lastly,

  someOtherTime = { display = "Y", type = "elapsedTimer" }

  For progress sources that are past time stamps.

* Stacks, Unit count, etc are all potential progress sources now.
* On the Display tab, the progress source can be selected from any trigger.
* Conditions can switch the progress source
* Ticks progress source is configurable and can be different from the main aura. This can be used via custom trigger to augment a main trigger
* state.autoHide can be a time point at which the state should automatically hide.
* Some behaviour changes, e.g. animations now observe the paused/remaining time and min/max progress settings

* Probably some regressions

Fixes: #4527
Fixes: #1449

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #(issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mrbuds** [comment]
I have not review code yet, i'll test functions first and report errors


Got 2 errors while doing this
- new aura
- progress source = trigger1 + Time since initial application
- set maximum progress = 60
- trigger tab: added renewing mist in name field
- close wa options => i have these 2 errors
```
!WA:2!DrvZUnsrqyBzyrmiHsmlreehIcz3vWHvBSi5aNWJJ9MGCSnJNqcCXUNzk7PjJ7E2U7XojNy9f2lCXpc(aN4KFe8tWilEcYbEaYtav3ZyZURT0O6VURVQ6VQk2O8OYbLdEZZMt95SU8eHp8vfwrsuHCr7yfLZKwlib)wIubbNtUz)JFH422dgib1P)qsHc)EHcfwqy(y4D4uMYRw9wU1Dw5Z5rb8jSUtOXq)LRvRhmecT15Q)uLGoCiiKF6tf5I)LircTiJG(ZijccdLKFP3HhEe(3bgd41FkqIuH3lt8m6DeWa6noD7uVzZPYyik6SaP1g3DtgGUx0Rw1UU966w1X1oHrvEXrKBbHJjbw2QBJbhDcRmpa8WJ4IgeNwVzNgx0CwclhDwXBt8v0XGBM(58a4Vl8aw0GGrI(zSuW21F(W1aexfXIVYHGnWWzegDKwIDSJureQglbIe6QeaBOk8Js31MXzWQaeb6O6PXJqcytkqovhQgpPhypIqzns)A8aPhK(K0NM(S0d8gqzuz47BglejrPVqiCo2nCGH6NYVFN0DxHQEe)Rhk4jSG3844Yk4gvpzibFGUk7PTy8UgJMpd4ce(9K5cPhmBJV9FImER36414rCXpwSyXs3NzfIgyOf2vVWTD8NzmIKlUUF4FjnqfAxfvFilr0BGaJXxVkJs9l5WzPXVMeshCB6JMl4kSYCrJ2TA3QE6UcSO0Xm3eOVbgLWFZYRaMkERgc6D79tjKaSRq2Z19Dk81zALX2eUi4sbjE6L5czaymvs9IG(518Br7J3(SwTQ70ZUTRB7ZDo7LN6UAtQ7sVd2nVIU6DYJ2RHS1(c3MN1Q()UAyeFsdb8QeG5FBNp4fpVYrzvN2Xs9NtYPjLMQ10NELxIsXzThdcKxpxBUPHA95l0YRlTzALABAnlXzTxU2sOjYnGZCZHu)RzGuwYCWU(KiOKTwm0yOjfDUTjB2yxceHEHaDyO612rCsqdpfEaMAhNrjrkQLTEIyN0F1YXpIiLAjBj2y0cXBHyPA(sgZAM(VVjklCUWqInddFSZ))gxjHgS4OrJ(o6H2WRAWwqzzmvmyR7Jf8HcSkY2T9TLqVufLe5shbc98mowCC6(wPFJLT2LL9DC(OIoKO4qsP5kU)4Sb7VO4F8j7tdCAbt2RsCzeE1YxQHlcWjDO)IbcCHcoxJ8Rsotme5hYE2BO9OrUx3Ao1R3YdhUhqhAjOm91dHXpE9ksnR(eQKGeTGqXnzpjD(WkhE4ZpAUENanBR801hO)SnJzPpQSSYjW4YJ)NR(Vp
```
```
1x WeakAuras/RegionTypes/Icon.lua:600: bad argument #1 to 'SetCooldown' (must be a finite number - Usage: self:SetCooldown(start, duration [, modRate]))
[string "=[C]"]: in function `SetCooldown'
[string "@WeakAuras/RegionTypes/Icon.lua"]:600: in function `PreShow'
[string "@WeakAuras/RegionTypes/RegionPrototype.lua"]:1035: in function `Expand'
[string "@WeakAuras/WeakAuras.lua"]:4469: in function <WeakAuras/WeakAuras.lua:4461>
[string "@WeakAuras/WeakAuras.lua"]:4553: in function <WeakAuras/WeakAuras.lua:4519>
[string "@WeakAuras/WeakAuras.lua"]:4663: in function `UpdatedTriggerState'
[string "@WeakAuras/WeakAuras.lua"]:4389: in function `UpdateFakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:4362: in function `FakeStatesFor'
[string "@WeakAuras/WeakAuras.lua"]:3066: in function <WeakAuras/WeakAuras.lua:2921>
[string "@WeakAuras/WeakAuras.lua"]:3089: in function `Add'
[string "@WeakAurasOptions/DisplayOptions.lua"]:186: in function <WeakAurasOptions/DisplayOptions.lua:175>
[string "=[C]"]: ?
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIWidget-EditBox.lua"]:70: in function <...ync/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:67>
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIWidget-EditBox.lua"]:114: in function <...ync/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:111>

Locals:
(*temporary) = WeakAurasCooldownnew_2 {
 0 = <userdata>
 expirationTime = Infinite
 SetDrawSwipeOrg = <function> defined =[C]:-1
 duration = 60
 useCooldownModRate = true
 SetDrawSwipe = <function> defined @WeakAuras/RegionTypes/Icon.lua:276
}
(*temporary) = Infinite
(*temporary) = 60
(*temporary) = nil
(*temporary) = "must be a finite number - Usage: self:SetCooldown(start, duration [, modRate])"

```
and
```
1x WeakAuras/RegionTypes/Icon.lua:422: bad argument #1 to 'SetCooldown' (must be a finite number - Usage: self:SetCooldown(start, duration [, modRate]))
[string "=[C]"]: in function `SetCooldown'
[string "@WeakAuras/RegionTypes/Icon.lua"]:422: in function `UpdateEffectiveInverse'
[string "@WeakAuras/RegionTypes/Icon.lua"]:411: in function `SetInverse'
[string "@WeakAuras/RegionTypes/Icon.lua"]:428: in function `modify'
[string "@WeakAuras/WeakAuras.lua"]:3167: in function `SetRegion'
[string "@WeakAuras/WeakAuras.lua"]:3050: in function <WeakAuras/WeakAuras.lua:2921>
[string "@WeakAuras/WeakAuras.lua"]:3089: in function `Add'
[string "@WeakAurasOptions/CommonOptions.lua"]:1752: in function <WeakAurasOptions/CommonOptions.lua:1750>
[string "=[C]"]: ?
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@BagSync/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <BagSync/libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@BagSync/libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@BagSync/libs/AceGUI-3.0-41/widgets/AceGUIWidget-CheckBox.lua"]:64: in function <...nc/libs/AceGUI-3.0/widgets/AceGUIWidget-CheckBox.lua:53>

Locals:
(*temporary) = WeakAurasCooldownnew_2 {
 0 = <userdata>
 expirationTime = Infinite
 SetDrawSwipeOrg = <function> defined =[C]:-1
 duration = 60
 useCooldownModRate = true
 SetDrawSwipe = <function> defined @WeakAuras/RegionTypes/Icon.lua:276
}
(*temporary) = Infinite
(*temporary) = 60
(*temporary) = nil
(*temporary) = "must be a finite number - Usage: self:SetCooldown(start, duration [, modRate])"
```

**Comment by mrbuds** [comment]
When using one of the "time since  ....." options, %p behavior does not change, which is good, but there is no text replacement to show the progress of these meta-value like %timeSinceLastRefresh %timeSinceStackGain etc..

**Comment by mrbuds** [comment]
Not important but something weird i noticed with an abnormal padding & positioning between select widget and it's menu
image
compare to 
image

**Comment by InfusOnWoW** [comment]
I am leaning towards not merging before 10.2, there are probably regressions which we won't immediately recognize and I think merging in a quiter period is better than immediately before a patch.

The way I conceptually think about it, is that the progress source should be independant of the text replacement, since you can already choose your source via text replacements.

That is for text replacement, you choose the **source** via %#.property. Thus because normal text replacement doesn't use the progress source at all, my reasoning goes that %p shouldn't either.

Well %refreshTime should work, just that there's no mention of it in the text replacements, because there's no good way to format it. We have a time format, but that works on a "duration" instead of a time point.

Technically adding a time point formatting is not hard, the hard part is the user confussion that there are now two different text formats for time, and it not being clear which one to use. It's an obvious missing piece,  which I decided to not do in this PR, but leave open for a further date. There are several potential ways to adress that, but I haven't spend much time considering them.

I'll take a look at the lua errors and the misaligned drop down.

**Comment by mrbuds** [comment]
With this PR "Dynamic Information" in trigger tab is in a weird state, it's close to be removable

Let's say it's set to "dynamic information from trigger 2"
- texts replacements can be migrated from %field to %2.field
- migration can be set progress to trigger 2

But custom code using aura_env.state.field instead of aura_env.states[2].field can't be migrated (technically maybe but we never touch others code)

--

"Icon Source" and "Progress Source" use different terminology for not that different concepts
- Dynamic Information => Automatic
- Fallback Icon => Manual - this one is trickier
I feel like Dynamic Information could be changed to Automatic for simplicity and consistency, not sure about fallback

**Comment by InfusOnWoW** [comment]
Right, I think the progress source terminology is better. And I think we can rename fallback to manual, it's not quite the same semantic, but it's close. And argueably more users are looking for a "Manual" Icon instead of a "Fallback" Icon.

Yeah that's the direction. I want to make the Dynamic Information kinda obsolete and instead allow the user to choose where various information comes from. That's a long road and after working on this for a year, this only chips away at it. 

At the end I think it'll require a backward incompatible change, which basically makes "Dynamic Information from first active" the only option and no longer configurable. So that would break all auras that use a explicit different setting. I don't think that'll happen for the next expansion.

Now there are other state variables where the dynamic information matters:
* texture (which I think can be ignored, no built-in trigger sets this and it's only for custom triggers)
* anchoring, mostly via .unit, where I have no idea 

But the big one is **clones**, the dynamic information setting decides which triggers clones are shown. The rough idea there is to add a "Visibility" configuration similar to how conditions work.

So that Visibility would consider the "union of all cloneIds", and with some clever checks allow for backwards compatible, e.g. a 
"If trigger 1 Has Clone" check is the same as setting the dynamic information to trigger 1. And a "First active trigger has clone" check would mirror the current "Dynamic Information from first active" setting. 

The visibiliy check should also have access to the states so that you e.g. check a combination of things in the states.

With that the Dynamic Information setting is close to obsolete then.

**Comment by mrbuds** [comment]
Not a blocker:

With an `Aura` trigger, i get options for Time since init application, last refresh, stack gain, stack lost, but none of "Time since" options have a text replacement shown on tooltip. It was added for `spell cooldown` trigger with text replacements for since [charge gain, charge lost, ready] options

`Spell Id` show as progress choice for triggers Combat Log, Cast or Spell Cast Succeeded, i think `type = "spell"` shouldn't be on the list

Blocker:

Tick placement delete button doesn't work

https://github.com/WeakAuras/WeakAuras2/assets/189656/6f70cd65-9d25-48b6-88e4-228e32ade4e3

Some other tick options widget doesn't work (no lua error)

https://github.com/WeakAuras/WeakAuras2/assets/189656/96109ab0-9f3f-4bc4-bcf4-8a53adf0f1b5

**Comment by mrbuds** [comment]
Had this error while doing Fyrakk HM

```
5x WeakAuras/WeakAuras.lua:4473: attempt to perform arithmetic on local 'expirationTime' (a nil value)
[string "@WeakAuras/WeakAuras.lua"]:4473: in function <WeakAuras/WeakAuras.lua:4430>
[string "@WeakAuras/WeakAuras.lua"]:4625: in function `UpdatedTriggerState'
[string "@WeakAuras/GenericTrigger.lua"]:857: in function `ScanEventsInternal'
[string "@WeakAuras/GenericTrigger.lua"]:803: in function `ScanEvents'
[string "@WeakAuras/GenericTrigger.lua"]:1075: in function <WeakAuras/GenericTrigger.lua:1060>

Locals:
Skipped (In Encounter)
```

**Comment by InfusOnWoW** [comment]
@mrbuds Should be all fixed now. For the elaspedTimer text replcements, I added them to BuffTrigger too, even though they are currently pretty useless.

For the formatting I see two options:
a) Add a time point formatter, which subtracts GetTime() before formatting
b) Make the existing time formatter type-aware, that is if the time formatter is applied to a elapsedTimer or timer state variable, it should automatically subtract GetTime(). 

I'm not 100% sure yet, which one I prefer, having two time formatters is less magically, but probably worse for the user. So I think I want to look at b)

Addtionally currently only %p text is replaced each frame, so currently there's some logic missing on how formatters can advertise that they need to run every frame.

I don't think it's absolutely critical to have that before merging, though I don't think it's that hard to implement.

**Review by mrbuds — APPROVED** [review]

**Pull request merged**
