### PR TITLE
Change progressPrecision to use floor

### PR DESCRIPTION
**Pull request by asakawa-k**
Having rounded numbers for a timer instead of floored feels odd, especially when showing no decimals, zero shows for half a second. Leaving the totalPrecision using Round seems fine though so I haven't altered that stuff.

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
So. I just looked at this again. And, there's a additional wrinkle, we aren't the only one formatting those numbers. There's the very popular omnicc addon and recently Blizzard added thier own formatting.

OmniCC's formatting matches our current formatting.
Whereas Blizzard uses ceil not floor.

Thus this PR would make us different from both.

**Comment by asakawa-k** [comment]
Hmm, Blizz use `ceil` on `SecondsToTimeAbbrev` but `SecondsToTime`, which is used more often, defaults to `floor` unless told to roundUp. That is done in `StatusBar` timers and `BaseTextTimerMixin`, tooltip CDs. But left as floor in a bunch of other areas. 

I hadn't realised this was such a mess. 
Or that OmniCC used Round too. 
But maybe we can at least agree that Round is the least accurate/most misleading option?
In terms of trying to judge when a text timer will end, if you're following the rhythm of the seconds ticking away, the 0 shows for 0.5 seconds then the timer ends.

**Comment by InfusOnWoW** [comment]
So Blizzard isn't even consistent in their own handling. Interesting.

**Comment by Stanzilla** [comment]
What do we want to do here?

**Comment by InfusOnWoW** [comment]
I think we need a solution, but a different one. It's something I want to tackle later this year.

**Comment by emptyrivers** [comment]
Arguably, this is in the scope of #1618, so i'm closing it. If somebody disagrees we can keep it open so we don't forget about this pain point.

**Pull request closed without merging**
