### PR TITLE
add custom dynamic info

### PR DESCRIPTION
**Pull request by asaka-wa**
# Description

Sorry for removing the old PR and replacing with this one. It was easier than trying to merge stuff since that old branch was made, and there was very little investment there. 

So this now adds a Custom option to the Dynamic Info selection with its own Code Block. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by asaka-wa** [comment]
A quick Aura to see it working:

```
!WA:2!DvvZYTTnq4OrTt7q3FIvsCTBsBz8mntYLoTQJZHEtuwkXTksQK0XotNoMGKqKiMcGfauYY3Ip0j9QEe05o9GEe8tag2o9bWhYdGFc6cijN4QdslwS4B3VfFluL21gwlUw8R3EgjIr9yf8i89UrjQqMY49YLegvyXN0BWabwwzoIgb(7ZiuzyZwD9B5wgXyzXSXuVXKCCW5Rw2kobN6Obn4mjNKKG5I)6b8LMVXrojh7kYXzzxikcXJWuPxXGbKtMFuZgE(h553W1FwmoeC6dXYFARo9BVFN81le4JsWumNe5LYg3JguETLZeWpnYgJMiCPOHyHvjhJY805QlSEMpbQa7(OSHLASeR2i4mJ5EXclNckrgMNHMG5UMIlFRMlzMDFolHJfc7hAW8rxrG(CmqaxV(T60zQgAjhfDCW0RYWMv(J)CAbDztW6bkR3Owt9rQpw9jk7nRU9FRwpqvtDl1wQpxDNsNm44ScP9prIow9zbQnTu3vDp1xO(s1TTuFvG6tv3uDFno)UXCn1w510jgfky8WNc0(zSyGyAFAkfCU2IigYgrOjbx82ynXPU7SMmAmXCTBkI7BnpMiEzbnssgHRJOtY3iQqizd3Dc0Cjr7rhW6Wsir5pAGjkg9HYhzzBZXYco1w(lF)VAJOX21TzC7VZ2ctJZxhzGZFrFqN67DJlbnfMtrzphukakjxEmgN3a6DrsxeGB6uboBGr7PEFqziqqcqsC6mO)7It018pSHATsyzi04s4ScA8RVDEnj(e5rIueC7D4sLC(wgNMVgW4drqalnCOmkE6vBV9xlYV57GqtwgJ)JvQuP6fl8UQOCASVFV8BzCcZpmaks0bKyzQtdy5LlYf5eCSX5Rkxmm9ILv05M9Fj0BjdMaeKZKa58bNoD71TLAnoWlDmZmbgzkJQWNPljbOrVzBo5u7FUafdngKTV)14(QmvA8nMXJpGJYp7GLglkGrebjmdhSKZVZaF(671TBl3JC65737zU79KN6xEvQ9iNI3AjJo8A5rVRzaU3((D2RBR)TmjJnUnh)BfyA0K(V33(n13zb70Bmx)1keotVqF4YWcPKr7ncZHzYzA3DW0ez6DmXVIzt1lAEvNrl2FYkpPo6ntnz3pfgOOWiCvZj8Iqz4fMDiG71njWb6lyEAykMKKkFLtgdf3oucHsLB4oSitsSC0YZnubwUrziHqB5iGwH2yg3Oj1LV6dDrz5POQtruIwxWOp2virCz7ZXib2tYnS5dGj4DkJ1YAiKJ0VrYfy4n0yXz64myTJZqeH2wTiAfr9s1XQDchqOer6)39CcDHQgWZY5ugByfoYmLkESkXsn0YboN0AMKfnAXG3MvcoCBsC9U4XUVvLnFahEadkuqyv9Yfx0T1U01uOxt3wT66o2iSdHcEajXItOAiXP1liXZ35fJo95D71y32hMF7v)lHwEVlrGafxC6SORE7X6SvrKYpz5LBnr9DXJQn6Fo8)(
```

**Review by mrbuds — APPROVED** [review]

**Comment by asaka-wa** [comment]
Tbh I would like someone experienced to take a look at this one. 

The other PR's conflict was a couple of lines and it was clear that I can just keep the incoming change. 

On this one, I only added a single line to an otherwise unchanged file but it's highlighting a massive amount of code as conflicting.

**Comment by InfusOnWoW** [comment]
yeah don't worry about the conflict, I'll resolve it once I get to the PR. Surely that's soon...

**Comment by asaka-wa** [comment]
Okidoke. Thanks very much. 

I am curious why my 2 recent PRs have had these conflicts though. If there's something I should or shouldn't be doing to prevent them popping up at all then please do say.

**Comment by Stanzilla** [comment]
> Okidoke. Thanks very much.
> 
> I am curious why my 2 recent PRs have had these conflicts though. If there's something I should or shouldn't be doing to prevent them popping up at all then please do say.

Not your fault, just happens when someone else touches the same part of the code

**Comment by InfusOnWoW** [comment]
The way to prevent that is to review and merge PRs faster. But I'm always behind on reviewing things, though I'm slowly reducing my backlog.

**Comment by asaka-wa** [comment]
👍

**Comment by InfusOnWoW** [comment]
I did indicate a few times already that I was sceptical about this because dynamic information is a concept that is going to be less interesting.

I finally had some time to map out how the systems should evolve.

So currrently the the trigger that provides "dynamic information" is important for:
1) Clones, only the clones of the DI-trigger are shown
2) Text replacements, where the DI-trigger handles the text replacements without a explicit trigger
3) Progress Information

Now the plan is this:
For 3) Use a similar semantic as for icon replacements. That is enable the user to be explicit on which trigger gives the progress information. (Also hopefully enable the user to select other parts of a state, e.g. stacks as sources). With an automatic mode that still uses the "DI" trigger.

For 2) Do nothing special, there's already a way to be explicit on which trigger provides the DI, so it's good enough. 

For 1) Replace the whole system with a per state visibility function.
That is provide a condition-like interface to select which basically allow just setting visibility to true or false **per state**, so that is evaluated per state. And basically allow checking all kind of state variables.

Now the biggest question was, whether that is possible to do in a backwards compatible way, and I believe it is. But only if we don't merge this PR.

The existing setings map in this way.
DI set to Trigger X is mapped to:
> If "Trigger X provides clone" => visibility: true
DI set to First active Trigger is maped to
> If "First active Trigger provides clone" => visiblity: true

These checks above need to be "AND" with:
ANY: nothing at all
ALL: "and if all triggers active"
Custom activation
> If "legacy custom activation" => visibility: true

And note that this means that the custom activation function is run **per state**. Which is obviously not something that can happen if the behaviour of this PR is implemented.

In that world since DI doesn't control which clones are shown, it's far less important.

Btw, I'm working on the progress bit, and the whole system is something I really want to do.

**Comment by InfusOnWoW** [comment]
One bit that I forgot is anchoring. The current anchoring based on "unit" of the dynamic information state, can be thought of as the "automatic" mode the others have. The obvious extension there would be to make it configurable from which trigger and property the unit is taken. 

So conceptually that fits pretty well, and maybe we'll eventually do that.

**Pull request closed without merging**
