### PR TITLE
re-enable model region for classic

### PR DESCRIPTION
**Pull request by mrbuds**
# Description
After seeing WeakAuras was forked on a chinese forum with models support https://bbs.nga.cn/read.php?tid=22060034&rand=116, my tests show that wrong models does not crash the game anymore.

I use the same ModelPaths.lua found on nga.cn forum for classic

### CODE REVIEW

**Comment by mrbuds** [comment]
I need to test the generated classic package to make sure i'v not forget anything

**Comment by Vardex** [comment]
The fork also add some options for `Model` region and `barModel` subregion like portrait zoom and cam distance scale.
It might be a good idea (maybe in a different pr) to add those.

**Comment by mrbuds** [comment]
should be ready now

**Comment by mrbuds** [comment]
woops it's not ready found something

**Comment by mrbuds** [comment]
need to fix model subregion picker for classic

**Pull request merged**
