### PR TITLE
Multitoc for BCC & Classic

### PR DESCRIPTION
**Pull request by mrbuds**
# Description

Package Classic and BCC libs & specific files for both packages, and let the new multi toc feature handle which files to load.

The goal is to have a single package work for both "classic era" and BCC clients, so if we have too much issues with people using wrong version of the addon we can use this.

For reference: https://github.com/Stanzilla/WoWUIBugs/issues/68

### CODE REVIEW

**Comment by Stanzilla** [comment]
So if we want to move to a single package release, to avoid people downloading the wrong one, we would remove the extra `.pkgmeta` files and move everything back into one. Then also rename the default toc and add `-Mainline` to it.

I don't quite see the benefit, apart from the user issue, though.

**Comment by mrbuds** [comment]
A benefit for me is i will be able to use  my local git repo directly on bcc, currently i use alpha builds from curseforge (packaged), do my changes and copy the changes to my local copy of the repo

**Comment by InfusOnWoW** [comment]
Yeah it would be nice to have that work.

**Comment by Stanzilla** [comment]
Going to look into it more, thanks guys!

**Comment by mrbuds** [comment]
> 
> 
> So if we want to move to a single package release, to avoid people downloading the wrong one, we would remove the extra `.pkgmeta` files and move everything back into one. Then also rename the default toc and add `-Mainline` to it.
> 
> I don't quite see the benefit, apart from the user issue, though.

updated with this change

**Comment by mrbuds** [comment]
BW Packager can't find toc file

`Could not find an addon TOC file. In another directory? Make sure it matches the 'package-as' in .pkgmeta`

**Comment by Stanzilla** [comment]
the proper multitoc stuff is not in the main branch yet either

**Comment by mrbuds** [comment]
for reference https://github.com/BigWigsMods/packager/tree/multitoc#whats-new-with-v2

**Comment by Stanzilla** [comment]
Is there any mode you prefer? I would be fine with what we currently have but you mentioned you want split tocs because of easier testing in classic?

**Comment by mrbuds** [comment]
Using multiple toc files indeed make it easier to dev weakauras on multiple clients.
Also if we choose to use a single package for all 3 versions it will definitely solve the long time issue we had with curseforge distributing wrong version for a client, but that imply increase a bit the size of the package for all versions as retail version would include tbc & classic specific files & libs.

**Comment by Stanzilla** [comment]
Hrm, to make testing easier, you could create the toc files locally and add them to .gitignore, no?

**Comment by mrbuds** [comment]
Mhmm true indeed i didn't think about it, but i'd have to copy them again when i checkout an other branch/repo

**Comment by Stanzilla** [comment]
I thought that would leave ignored files alone but I haven't checked in a while

**Comment by InfusOnWoW** [comment]
I'd like to have multi-toc in, it would make my life easier too.

**Comment by Stanzilla** [comment]
`WeakAurasModelPaths-Mainline.toc` needs to be updated to remove the packager keywords as well

**Comment by Stanzilla** [comment]
Also looks like we might need an empty `WeakAuras.toc` because CurseForge requires that this file exists. Not sure if it will accept the empty file or if we have to fill it but let's test.

**Comment by mrbuds** [comment]
After renaming Mainline files it produce 2 artifacts instead of 3

**Comment by mrbuds** [comment]
Looks like -Classic.toc files are not handled

**Comment by Stanzilla** [comment]
Looks good to me?

**Comment by mrbuds** [comment]
Right, we'll see what are the best practice to use when multitoc branch is merged and is stable

**Comment by mrbuds** [comment]
Moved to #3722

**Pull request closed without merging**
