### PR TITLE
Add GetData method

### PR DESCRIPTION
**Pull request by emptyrivers**
to fix a dumb bug with restoring from migration snapshots

### CODE REVIEW

**Comment by emptyrivers** [comment]
Don't merge quite yet, I found another bug.

**Comment by emptyrivers** [comment]
ready for review now, everybody

**Comment by emptyrivers** [comment]
Fixes #2064  (the root cause, anyways)

**Comment by mrbuds** [comment]
Seems good to me except the error i have reported on Archivist repo <https://github.com/emptyrivers/Archivist/issues/2>

**Pull request merged**
