### PR TITLE
Add Sound Heartbeat Single

### PR DESCRIPTION
**Pull request by Jieiku**
# Description
Add a single thump heartbeat sound

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested

Tested Live in the game.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] Was not necessary to comment my code
- [X] Was not necessary to make changes to the documentation
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
Where did you get that file from?

**Comment by Jieiku** [comment]
https://uppbeat.io/sfx/heartbeat-single-1/61/1336

**Comment by mrbuds** [comment]
<https://uppbeat.io/pricing>

That looks like a no go

image

**Comment by Jieiku** [comment]
oh, so not really free then, I can try and find an alternative for the sound file, something like a heartbeat sound should be easy enough to find.

**Comment by Jieiku** [comment]
I found some CC0 ones here: https://opengameart.org/content/heartbeat-sounds

Will see which I like best, convert to ogg, then adjust the pull request.

**Comment by Jieiku** [comment]
Feel free to squash the commits, The sound file used is now heartbeat_slow_0.wav from this page:
https://opengameart.org/content/heartbeat-sounds

It uses a CC0 license.

I pulled the sound file into Audacity, Trimmed it to a single heartbeat, adjusted the amplification, then converted to ogg.

**Comment by Stanzilla** [comment]
@Jieiku Hey can you restore the branch/repo?

**Comment by Jieiku** [comment]
No but I can open a new pull request.

**Pull request closed without merging**
