### PR TITLE
Fixing #3225

### PR DESCRIPTION
**Pull request by Kazimazi**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested

- Logged in and used weak aura used in original issue.

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
The commit message should contain what problem this fixes.

**Comment by Kazimazi** [comment]
It does, links you to the appropriate issue page.

**Comment by mrbuds** [comment]
You can check https://github.com/WeakAuras/WeakAuras2/pull/3179#issuecomment-873159531 to see how to change commit message

**Comment by Kazimazi** [comment]
Thanks for the aid.

**Pull request merged**
