### PR TITLE
Switch to single build mode

### PR DESCRIPTION
**Pull request by mrbuds**
Continued from #3100 (rebase was nightmarish, redid it by hand)

Tested on Classic, TBC, Wraith Beta and Retail using a hardlink from git repository, no error on start or on open options.

Followed https://github.com/BigWigsMods/packager#building-for-multiple-game-versions https://wowpedia.fandom.com/wiki/TOC_format#Multiple_client_flavors and precious advice from Meoww

~~Next step is to change IsRetail/IsClassic/.... tests to take advantage of conditional lua file loading, but that will be for an other PR.~~

### CODE REVIEW

**Comment by mrbuds** [comment]
> Next step is to change IsRetail/IsClassic/.... tests to take advantage of conditional lua file loading, but that will be for an other PR.

Nop i'll have to do it now, packager do not accept build type keywords
image

**Comment by Stanzilla** [comment]
We could also move to just uploading one zip, I think all sites support that now

**Comment by mrbuds** [comment]
> We could also move to just uploading one zip, I think all sites support that now

I was waiting to fix build errors to see how it's packaged

**Comment by mrbuds** [comment]
Looks like it's what it did 
image

**Comment by Stanzilla** [comment]
> Looks like it's what it did image

Oh haha, I commented without looking at the changes :D

**Comment by InfusOnWoW** [comment]
This is great! If the packages work, we should merge this immediately.

**Review by Stanzilla — CHANGES_REQUESTED** [review]
Looks good, just needs minor version bumps in the Ace widgets, will test in game soon

**Comment by mrbuds** [comment]
> Looks good, just needs minor version bumps in the Ace widgets, will test in game soon

Done, also noticed some widgets didn't have the lib check and fixed it

**Review by Stanzilla — APPROVED** [review]

**Comment by InfusOnWoW** [comment]
I had a quick look, and everything looked normal. So as far as I'm concerned we can merge it.

**Pull request merged**
