### PR TITLE
Add the LoC type NONE

### LINKED ISSUE #3782: LOC trigger returning a 'NONE' type
### Description

While trying to make a WA that would replace the default blizzard LOC indicator, I observed that whenever I was taking Oribos portals to go up and down (any other portals seem to act the same way), it would return a 'NONE'.
I don't know if this is intended, but I made this because I used to have another custom WA working with custom functions and it didn't show this type of LOC ever.

I've been able to make a workaround by setting a condition up like 'if name contains LOSS_OF_CONTROL_DISPLAY_NONE then relative X-offset = 1940'

PS: if you use the provided WA, make sure to delete the condition before testing

### WeakAuras Version

WeakAuras 4.1.1

### World of Warcraft Flavor

Retail (Default)

### Tested with only WeakAuras

- [ ] Yes
- [X] No

### Lua Error

_No response_

### Reproduction Steps

1. Create a WA with the following trigger: Player/Unit info > Crowd Controlled
2. Set up a %name in the display tab
3. Use an Oribos portal to go up/down
4. Look at the returned text

### Last Good Version

_No response_

### Screenshots

image

### Export String

!WA:2!TrvZUTTrq4i4cyuwGIu1wJ2cJIGG6KwFWa2TWa5OOSuJdKfDjPRD6HsTK7qXnMAxIDxkz5BrNYz)iOZ9KEe8taHqFc8JGo0ZDwskB3F0bHzND2V5BM5ByJUnh1K2K(HVBolsW9e5Yiy7NiN6ehRaDJfeEuIqEQGX1HT703VJ7YiHiLkMW9MWYGb3U(yh6qiX2GYGzAjB4qqQ(0xiRn)lzUc6tgbjznrRasOsidFnqsprqHb3PYdHXax7LhhZUArq7wE(bE(TC9NzcpNZ0dwGyRLIu)PzGTN)z9DlFs2tBlftOpRD1TPa9E0ovciAUEN2PxpBdgHzPKPG0LJmrzntLbPPhtvw39aNk5ZkZ5hLUKshuiePx7uIsLyRr3fF58kFMyKVUL7jDpR3n586I2k7ZirA2yWV6Sb6)4jRWEji5K0Ff7qmb)YvxcqwlKlrAxIMjgCJcsJR652o((oNGzrr05sIgsMJfNlmeFOA3Tk2EjEmKeD5qPiNt)Wwzn1Wv6avcbhkxupgZ(6sNL)flKJiya1g2CbhU5(RL7S)EMMt2tFemTfPc5BAG)URY7A6z36mFNSpV0jjxlq8yrNZO6e7w4XvvjKDfqlD((LvYP3wtRBlV)D5knlEAXhnxk0yf6JoT770VtX2sS4mXmVmWOsASb(7M6kHRN35QmjOutit)hv(6uSS03eHKEUKKn78AJQmpMPyHPWG6I9rA9BDodL6bvD)SD(pDV937rIJANf7U8EAvQhqm6DC)op41JDnStDp4(rZ3()aUzcCpQHjaByI(92PccTRTcbzl3r5PAMLTr0SvXBSCJmIsJvOMKIkFJ5CzPmXWLInlx7AxVRIcruPbdUHWzMzMGFORstK6UfBxS7TarbEAjWhQt2Cj1O7WqcmkEPcWkNQMzIPe5DThry8Yhw4UzHxHFXziPJzCMk5F7E26VwmyUbgMbx138c3Oei6YUfF8gpxKnhFk97F5oQx(dZgtKmcoISnDe3XK0CiB7EoEEboDdA70331PxWrh7DAVwVnWOzKrje(qaXS43pA6SmPa5SE6QRQA3UqkXSqkn7LyQpS4xSSrMQTko3swhud7RfIrncrggZgAnxlIgxTQ(vnge8CgDvpHs9mr86p54(GYCrSezk28iAYN4oPu1VQAI31CJPLf612TtN(hKZOlEx0PxeDq)F7A4NLmUjnqIljnlHSr2xSUzz2ioIPmncAYcktz(k2Xi9c3)hp4vV6WfmELybPO1sCreZMtwzbA1u5(t7T)E73C8FEXFp

### PR DESCRIPTION
**Pull request by asaka-wa**
# Description

The LoC Type "None" wasn't handled. 

Fixes #3782

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

I logged in and tested it
- [x] Test A
- [ ] Test B

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
So what about the "I have tested this" checkbox?

**Comment by asaka-wa** [comment]
I don't see a checkbox labelled that.

**Comment by InfusOnWoW** [comment]
The "Test A" / "Test B".

**Comment by Nightwarden24** [comment]
Perhaps, in addition to adding a value to the type, add an option (toggle) specifying how this event should be displayed to the player. I mean handle [displayType](https://wowpedia.fandom.com/wiki/API_C_LossOfControl.GetActiveLossOfControlData) with value 0 like [Blizzard](https://www.townlong-yak.com/framexml/live/LossOfControlFrame.lua#119). This is not [the first time](https://github.com/WeakAuras/WeakAuras2/issues/3364) the issue has been reported.

**Comment by asaka-wa** [comment]
Is the linked ticket relevant? I don't see it.

**Comment by InfusOnWoW** [comment]
It is, the original reporter complained about the LoC trigger staying active, which I fixed. 

But maybe the trigger should not trigger at all for taking a portal. After all, the default UIs LoC widget doesn't show up if you take a portal. I'm pretty sure I didn't consider that when I fixed the LoC trigger to not stay active.

Though I'm fine with just adding it as type that you can select.

**Comment by asaka-wa** [comment]
I see. 
This PR, as a fix for the ticket I was responding to, requires basically adding an additional trigger for NONE with Inverse ticked. That's a bit awkward. Though having the WA trigger carry more info than the default display seems like a positive thing overall because you can never quite predict what people will want to see.

**Comment by Nightwarden24** [comment]
It was just a suggestion, nothing more

**Pull request merged**
