### PR TITLE
fix DBM trigger

### PR DESCRIPTION
**Pull request by mrbuds**
Use "[=[" instead of "[[" as string interpolation.

linked too #753 #754

### CODE REVIEW

**Comment by emptyrivers** [comment]
Why not use %q instead of trying to add quotes to %s? This is what %q is for, last I checked.

**Comment by Stanzilla** [comment]
Yup, should probably use that everywhere

**Comment by InfusOnWoW** [comment]
Point is, I just pushed a fix for the BigWigs trigger where I didn't use %q either. So I think we can merge this, and @mrbuds can decide whether that's something he wants to do or not.

**Comment by emptyrivers** [comment]
Well, I wasn’t suggesting to replace %s with %q wholesale. %q formats strings such that when they’re interpreted again by lua via loadstring or similar, they remain as string values, so it only makes sense to use %q when you want a string literal in the triggerfunction.

**Comment by Stanzilla** [comment]
In any case, a thing for a new PR

**Pull request merged**
