### PR TITLE
Refactor optionsframe

### PR DESCRIPTION
**Pull request by jgersti**
move and split CreateFrame.

### CODE REVIEW

**Comment by InfusOnWoW** [comment]
Can you rebase the pull request?

**Comment by Stanzilla** [comment]
Time to nit! Can we rename 
IconPick => IconPicker
ModelPick => ModelPicker
TexturePick => TexturePicker

**Comment by jgersti** [comment]
@InfusOnWoW  I wanted to wait till the smallpateches are merged.

@Stanzilla sure

**Comment by Stanzilla** [comment]
```
1x WeakAurasOptions\OptionsFrames\MoverSizer.lua:402: attempt to index global 'db' (a nil value)
WeakAurasOptions\OptionsFrames\MoverSizer.lua:402: in function `SetToRegion'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:721: in function `finishPicking'
...dOns\WeakAurasOptions\OptionsFrames\OptionsFrame.lua:753: in function `PickDisplay'
WeakAurasOptions\WeakAurasOptions-@project-version@.lua:6682: in function `PickDisplay'
...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:303: in function <...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:278>
```

**Pull request merged**
