### PR TITLE
add BAG_UPDATE_COOLDOWN event to "Item Count" trigger #929

### PR DESCRIPTION
**Pull request by mrbuds**
doesn't #929 :D

### CODE REVIEW

**Comment by Stanzilla** [comment]
I had tested that, and it does not fix it for me.

**Comment by Stanzilla** [comment]
oh also please remove the fix comment since it only fixes one aspect of it and we want to keep the ticket open for discussion

**Comment by Stanzilla** [comment]
> When Dynamic Information is set to trigger2, to get the cooldown, it does not update text, guess I did not realize trigger update is linked to that.

Should the display text `trigger update` fire for *any* trigger's update?

**Comment by asakawa-k** [comment]
That behaviour is, at least, what we've disseminated. That Trigger Update fires when the current Dynamic Info changes ins some way. (Side note, for a long time I thought that Trigger Update was identical to Every Frame because I kept testing it with timed Auras).

With a Healthstone tracker, whose main trigger is the item's CD, I wouldn't expect that the item count _could_ change without it also affecting the main trigger. Though perhaps the order of the events fired means that the count hasn't updated when the CD updates.

**Comment by InfusOnWoW** [comment]
Currently it should only fire for the active trigger updates, but with the %#.var change, it does trigger for all triggers.

**Pull request merged**
