### PR TITLE
Smallpatches

### PR DESCRIPTION
**Pull request by InfusOnWoW**
Various small patches

### CODE REVIEW

**Comment by Stanzilla** [comment]
In the future, it would help me quite a bit, if you could just list the newly added translations in the pull request. I have to add them to the translation system manually and sometimes miss them in the code.

**Comment by InfusOnWoW** [comment]
Okay, I'll try to do that.

**Comment by Stanzilla** [comment]
http://dev.deadlybossmods.com/rss/DBM_Alpha_Changes-r14433.html

**Comment by Stanzilla** [comment]
Left some more comments on stuff. Is there anything you really want to get done before the next release?

**Comment by InfusOnWoW** [comment]
Yeah let me fix the DBM trigger then and investigate the PLAYER_MOVING thing.

**Comment by Stanzilla** [comment]
@InfusOnWoW Okay, sounds good. I also added some input to http://www.wowace.com/addons/weakauras-2/tickets/403-load-conditions-bug-lua-error/ in case you did not notice.

**Comment by InfusOnWoW** [comment]
Right, that bug report too, and then your comments in that commit, I'll do that today or tomorrow.

And I'm planning on doing a short video showing the new bigswigs / dbm triggers.

**Comment by Stanzilla** [comment]
Alright, I'm currently going through WA.lua, cleaning stuff up here and there and fixing the horrible indenting. I will only commit that after your stuff so I don't give you any trouble with the whitespace changes.

**Comment by InfusOnWoW** [comment]
Here you go: https://github.com/WeakAuras/WeakAuras2/pull/11

Some notes:
I added a version check for DBM. I could have also supported both the old callbacks and the new ones, but I guess people update DBM frequently enough, that it doesn't matter much if only the newest version is supported.

The PLAYER_MOVING thing is pretty funny, apparently to get the one leg forward pose, WoW is pretending that the user is pressing/release the foward button all the time.

**Comment by InfusOnWoW** [comment]
Ah wait with merging, I've found one small issue in the bigwigs options, I'll do one update later today.

**Comment by InfusOnWoW** [comment]
Okay, I've updated the merge request.

**Comment by InfusOnWoW** [comment]
Seems I forgot to include this patch http://www.wowace.com/addons/weakauras-2/tickets/363-support-for-arena1-5-uid-as-specific-units/ in the merge request.

**Comment by Stanzilla** [comment]
https://github.com/InfusOnWoW/WeakAuras2/commit/c668412df1dac6f1c7a7d7c458436fb08c468ea0 Doesn't look right, if you look at my commit https://github.com/InfusOnWoW/WeakAuras2/commit/6dfb997413dcafd5113f1ca87a0fe4dc91362a26 you can see that I did not even touch that line, did you maybe forget to merge this one? https://github.com/WeakAuras/WeakAuras2/commit/08f83cf49543061e879381788ad6ead7fe78038c

**Comment by Stanzilla** [comment]
I cherry picked the others already though.

**Comment by InfusOnWoW** [comment]
Hmm? I don't see any changes when I fetch. Anyway, the updated pull request contains the same patches except the last one is new.

**Comment by Stanzilla** [comment]
Okay, I might be blind, pushed the last one, too. When do you want me to push my indenting changes?  I guess it will mess up with your WIP patches quite a bit and you would have to handle a few merge conflicts, I can delay pushing that after you are done with those?

**Comment by InfusOnWoW** [comment]
Nah just do it. I'll be fine...

**Comment by InfusOnWoW** [comment]
And thanks for merging.

**Comment by Stanzilla** [comment]
Pushed. Thank *you* for your fixes :) I hope the file is more readable for you too now.

**Comment by InfusOnWoW** [comment]
So, as to the global that you mentioned in WeakAurasOptions.lua. I think that's my fault, and a simple copy and paste error. I think you can safely remove the msg from that call to ShowOptions(), but I don't understand what the msg is

This ShowOptions() is to reshow the options dialog after combat ends and we have hidden the options on combat start. So if you figure out what the msg actually is, then we would probably need to store it in the code 4 lines above and then pass it to ShowOptions.

**Comment by Stanzilla** [comment]
Yeah I realized what it is and what it is used for but not where it came from. Just going to remove it then..

**Pull request merged**
