### PR TITLE
update WeakAurasModelPaths from wow.tools csv export

### LINKED ISSUE #2829: Model Path Module Missing Shadowlands listings.
## Describe the bug

Not much else to say except the current expansion doesn't show in the 3D Model Paths module when creating an aura.

**Do you have an error log of what happened?**

```plaintext
PASTE ERROR HERE
```

### To Reproduce

**Screenshots**

**Did you try having WeakAuras as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of WeakAuras are you using?**

**Are you on World of Warcraft Classic or Retail?**

- [ ] Classic
- [ ] Retail

**Was it working in a previous version? If yes, which was the last good one?**

### PR DESCRIPTION
**Pull request by mrbuds**
# Description

To get source csv files from https://wow.tools/files/ click on "Listfile" >Community CSV Retail and/or ClassicRetail

image

Fixes #2829

### CODE REVIEW

**Comment by StanzillaManticore** [comment]
Two things:

1) We could just run that in the CI to automate it
2) We could ask @marlamin for a ?latest API so we don't have to hardcode version numbers

**Comment by Stanzilla** [comment]
Two things:

1) We could just run that in the CI to automate it
2) We could ask @marlamin for a ?latest API so we don't have to hardcode version numbers

**Comment by mrbuds** [comment]
> 
> 
> Two things:
> 
>     1. We could just run that in the CI to automate it
> 
>     2. We could ask @Marlamin for a ?latest API so we don't have to hardcode version numbers

The files are not small and the script take quite some time to run on my computer.
Could CI run an automated update only if target's build has changed instead of running it for every new commit ?

**Comment by Marlamin** [comment]
Do you just need (named) m2s for this?

**Comment by mrbuds** [comment]
> 
> 
> Do you just need (named) m2s for this?

Hey Marlamin :)
Yes, only named m2 with their fileId

**Comment by Marlamin** [comment]
>We could ask @Marlamin for a ?latest API so we don't have to hardcode version numbers  

A latest build per branch listfile endpoint would need to keep track of the current build for a branch and that's kind of a pain for me to do right now in the CASC backend that generates the listfile. I added a quick separate API that returns the current build config for a certain branch that you can use: https://wow.tools/api.php?type=currentbc 

> Yes, only named m2 with their fileId  

I added an optional `typeFilter` GET to the listfile downloads that returns only filenames ending in the specified string. 
e.g. `https://wow.tools/casc/listfile/download/csv/build?buildConfig=26291f284f42494375d511d1fc120216&typeFilter=m2` will only returns filenames for that build ending in m2. Hopefully that saves a bit of processing on your end of things.

A note I always give people who want to rely on WoW.tools for things, I give no guarantee of uptime/API stability

**Review by Stanzilla — APPROVED** [review]
Did you mark the .sh file as +x in git?

**Comment by mrbuds** [comment]
> 
> 
> Did you mark the .sh file as +x in git?

yes with `git update-index --chmod=+x ./wowtools.sh`

**Pull request merged**
