### PR TITLE
Anchor to a Frame

### PR DESCRIPTION
**Pull request by DarioGdR**
So this is pretty simple as you can see, and it easily works... it just have some issues that need resolving, they are all on the WowAce ticket.

There are errors and I'm trying to fix them, but maybe someone else that has worked with the Addon before can help me out.

http://www.wowace.com/addons/weakauras-2/tickets/284-new-functionality-anchor-to-another-frame/

### CODE REVIEW

**Comment by Stanzilla** [comment]
@dgdr1991 Any news here? I saw that you closed the ticket on Wowace, are you not interested in working on this anymore?

**Comment by dgdr1991** [comment]
@Stanzilla , I will probably not be working on this anymore, I totally forgot to close the pull.

Honestly I am really interested but also totally busy nowadays... and I if I recall correctly I was having issues fixing the couple of bugs and LUA errors because I didn't fully understand how the addon worked, which was quite frustrating because I was really close!

Anyway, sorry for not updating on this pull, if no one else finishes this I will probably do it when I've more free time.

**Comment by Stanzilla** [comment]
It's ok, just leave it open :)

**Comment by Stanzilla** [comment]
superseded by https://github.com/WeakAuras/WeakAuras2/pull/135

**Pull request closed without merging**
