### PR TITLE
Smallpatches

### PR DESCRIPTION
**Pull request by InfusOnWoW**

### CODE REVIEW

**Comment by mrbuds** [comment]
First test using classic package i get this error log
image

Error come from the line `return t[k]` of the function `MakeReadOnly`

**Comment by InfusOnWoW** [comment]
Should be fixed now.

**Comment by InfusOnWoW** [comment]
But I didn#t change anything around CheckNumericIds, can you export that aura?

**Comment by mrbuds** [comment]
I can't open options, i think that one come from https://wago.io/DJafP8F7S

[WeakAuras.zip](https://github.com/WeakAuras/WeakAuras2/files/5105272/WeakAuras.zip)

**Comment by InfusOnWoW** [comment]
Ah yes, silly me

**Comment by mrbuds** [comment]
looks good now

**Pull request merged**
